#!/bin/bash
# Project Links

PROJLINKS_FILE="${TODO_DIR}/project-links.txt"

ITEM=false
if [ x"$1" = x"projlink" ]; then

    [[ -z $2 ]] && echo "Error: Item number not found" && exit 0
   
    [ "$2" = "usage" ] && {
        echo
        echo "  Select an item and start counting the time you work on it"
        echo "  usage:"
        echo "      todo.sh projlink #ITEM"
        echo "      todo.sh projlink list"
        echo "      todo.sh projlink copy #ITEM"
        echo
        exit
    }

    [ "$2" = "list" ] && {
        shift
        shift
        /usr/local/bin/todo.sh listfile project-links.txt "$@"
        exit
    }

    [[ "$2" = "open" ]] && OPEN_LINK="Y" && shift

    # If the url is a mantis url, copy the issue number to clipboard
    [[ "$2" = "mantis" ]] && MANTIS="Y" && shift

    ITEM=$2

    shift
    shift
fi

# get the right activity and its summary

counter=0

while read line
do

    let "counter = counter + 1"
    [[ $counter = $ITEM ]] && summary=$line

done < "$PROJLINKS_FILE"

[[ -z "$summary" ]] && echo "Could not find activity number $ITEM" && exit 0

summary=`echo "$summary" | sed 's/\+[^ ]* *//g'`

[[ "$OPEN_LINK" = "Y" ]] && {
    #url=`echo "$summary" | awk -F'[:"] *' '{print $2}' `
    url=`echo "$summary" | grep -o -E "https*://[^ ]*"`
    echo "Opening: $url"

    google-chrome "$url"

}

[ "$MANTIS" = "Y" ] && {
    mantis_link=`echo "$summary" | grep -i "mantis"`

    [[ -z "$mantis_link" ]] && echo "Not a Mantis URL" && exit 0

    mantis_issue=`echo "$summary" | grep -o -E "https*://[^ ]*" | awk -F'[?=]' '{print $3}'`

    echo "Copying Mantis #$mantis_issue to the clipboard"
    printf "%s" "Mantis #$mantis_issue" | xclip -selection clipboard

    exit

}

echo "Copying to clipboard: ${summary}"
printf "%s" "$summary" | xclip -selection clipboard

